// Generated by CoffeeScript 1.8.0
(function() {
  var count, midi, parser, start, test1, test2, test3, test4,
    __slice = [].slice;

  midi = require('midi');

  count = 0;

  parser = function(port, msg) {
    var channel;
    channel = msg[0] % 16 + 1;
    switch (msg[0] / 16) {
      case 0xB:
        return ["/" + channel + "/cc/" + msg[1], msg[2] / 127.0];
      case 0x9:
        return ["/" + channel + "/note/" + msg[1], msg[2] / 127.0];
      case 0x8:
        return ["/" + channel + "/note/" + msg[1], 0];
      case 0xE:
        return ["/" + channel + "/pitchbend/", msg[1] / 127.0];
      default:
        return ___.apply(null, [void 0, 'message:'].concat(__slice.call(msg)));
    }
  };

  start = function(midi_in, port, virtual) {
    if (virtual == null) {
      virtual = false;
    }
    console.log("Opening port " + port + " - " + (midi_in.getPortName(port)));
    midi_in["open" + (virtual && 'Virtual' || '') + "Port"](port);
    return midi_in.on('message', function(deltaTime, msg) {
      count++;
      return console.log("" + count + ": message received " + (parser(port, msg)));
    });
  };

  test1 = function() {
    var midi_in1;
    midi_in1 = new midi.input();
    start(midi_in1, 0);
    return console.log('Test 1: Listening to port');
  };

  test2 = function() {
    var midi_in1, midi_in2;
    midi_in1 = new midi.input();
    midi_in2 = new midi.input();
    start(midi_in1, 0);
    return console.log('Test 2: Listening to port');
  };

  test3 = function() {
    var midi_in1, midi_in2;
    midi_in1 = new midi.input();
    midi_in2 = new midi.input();
    start(midi_in1, 0);
    start(midi_in2, 0);
    return console.log('Test 3: Listening to port');
  };

  test4 = function() {
    var midi_in1;
    midi_in1 = new midi.input();
    start(midi_in1, 0);
    start(midi_in1, 0);
    return console.log('Test 4: Listening to port');
  };

  'This code tests the node-midi functionality under different situations. Test 2 causes crashes while the other tests do not.\n\nSteps to reproduce crash:\n- Install MidiKeys on OSX 10.10\n- Launch MidiKeys\n- Install coffee-script if you don\'t have it\n- Checkout project and npm install in the root directory.\n- Run test2 below using `coffee midi-test.coffee`\n- Focus MidiKeys\n- Type random letters for around 30 seconds.';

  test3();

}).call(this);
